version: '3.8'

services:
  app-achat:
    depends_on:
      - MYSQL-DATABASE
    image: chaima12/achat-devops:1.0.0
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://MYSQL-DATABASE:3306/achat_db?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": null,
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    stdin_open: true
    tty: true
    mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=achat_db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
 

volumes:
  db: